[build]
  publish = "public"
  command = "npm install hexo-generator-feed --save;npm install --save hexo-helper-live2d;npm run build;npm install --save hexo-blog-encrypt"

[build.environment]
  NODE_VERSION = "14"
