[build]
  publish = "public"
  command = "npm install hexo-generator-feed --save;yarn install --save hexo-helper-live2d;yarn install --save hexo-blog-encrypt;npm run build"

[build.environment]
  NODE_VERSION = "14"
