[build]
  publish = "public"
  command = "npm install hexo-generator-feed --save;npm install hexo-renderer-pug hexo-renderer-stylus --save;npm install hexo-wordcount --save;npm install --save hexo-tag-aplayer;npm run build"

[build.environment]
  NODE_VERSION = "14"
